# notebook output을 위한 파일입니다.

# json 형식으로 저장되어 있습니다. formatter를 비활성화 하고 저장해주세요.

testcase_and_result = [
    {"que_number": 0, "lv": "", "kinds": "", "testcase": "", "result": ""},
    {"que_number": 1, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 2, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 3, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 4, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 5, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 6, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 7, "lv": 0, "kinds": "정렬"},
    {"que_number": 8, "lv": 0, "kinds": "정렬"},
    {"que_number": 9, "lv": 0, "kinds": "정렬"},
    {"que_number": 10, "lv": 0, "kinds": "정렬"},
    {"que_number": 11, "lv": 0, "kinds": "정렬"},
    {"que_number": 12, "lv": 0, "kinds": "정렬"},
    {"que_number": 13, "lv": 0, "kinds": "정렬"},
    {"que_number": 14, "lv": 0, "kinds": "정렬"},
    {"que_number": 15, "lv": 0, "kinds": "정렬"},
    {"que_number": 16, "lv": 0, "kinds": "정렬"},
    {"que_number": 17, "lv": 0, "kinds": "정렬"},
    {"que_number": 18, "lv": 0, "kinds": "분석"},
    {"que_number": 19, "lv": 0, "kinds": "타입 확인"},
    {"que_number": 20, "lv": 0, "kinds": "타입 확인"},
    {"que_number": 21, "lv": 0, "kinds": "탐색"},
    {"que_number": 22, "lv": 0, "kinds": "탐색"},
    {"que_number": 23, "lv": 0, "kinds": "탐색"},
    {"que_number": 24, "lv": 1, "kinds": "탐색, 동적 프로그래밍, 카데인 알고리즘"},
    {"que_number": 25, "lv": 1, "kinds": "탐색, 에라토스테네스의 체"},
    {"que_number": 26, "lv": 0, "kinds": "탐색, 슬라이딩 윈도우"},
    {"que_number": 27, "lv": 1, "kinds": "탐색, 슬라이딩 윈도우"},
    {"que_number": 28, "lv": 1, "kinds": "탐색, 투 포인터"},
    {"que_number": 29, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 30, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 31, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 32, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 33, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 34, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 35, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 36, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 37, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 38, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 39, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 39, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 40, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 41, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 42, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 43, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 44, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 45, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 46, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 47, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 48, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 49, "lv": 2, "kinds": "데이터 구조, 너비 우선 탐색(BFS)"},
    {"que_number": 50, "lv": 2, "kinds": "데이터 구조, 깊이 우선 탐색(DFS)"},
    {"que_number": 51, "lv": 0, "kinds": "그리디"},
    {"que_number": 52, "lv": 0, "kinds": "그리디"},
    {"que_number": 53, "lv": 0, "kinds": "그리디"},
    {"que_number": 54, "lv": 1, "kinds": "행렬"},
    {"que_number": 55, "lv": 0, "kinds": "행렬"},
    {"que_number": 56, "lv": 0, "kinds": "행렬"},
    {"que_number": 57, "lv": 0, "kinds": "행렬"},
    {"que_number": 58, "lv": 1, "kinds": "행렬"},
    {"que_number": 59, "lv": 0, "kinds": "행렬"},
    {"que_number": 60, "lv": 0, "kinds": "행렬"},
    {"que_number": 61, "lv": 1, "kinds": "자료 구조, 데큐"},
    {"que_number": 62, "lv": 1, "kinds": "자료 구조, 데큐"},
    {"que_number": 63, "lv": 1, "kinds": "문자열 처리"},
    {"que_number": 64, "lv": 1, "kinds": "문자열 처리"},
    {"que_number": 65, "lv": 0, "kinds": "문자열 처리"},
    {"que_number": 66, "lv": 1, "kinds": "문자열 처리"},
    {"que_number": 67, "lv": 1, "kinds": "문자열 처리"},
    {"que_number": 68, "lv": 1, "kinds": "순열과 조합"},
    {"que_number": 69, "lv": 1, "kinds": "순열과 조합"},
    {"que_number": 70, "lv": 1, "kinds": "순열과 조합"},
    {"que_number": 71, "lv": 0, "kinds": "집합"},
    {"que_number": 72, "lv": 0, "kinds": "집합"},
    {"que_number": 73, "lv": 0, "kinds": "집합"},
    {"que_number": 74, "lv": 1, "kinds": "집합"},
    {"que_number": 75, "lv": 1, "kinds": "집합"},
    {"que_number": 76, "lv": 1, "kinds": "배열, 병합"},
    {"que_number": 77, "lv": 0, "kinds": "좌표평면"},
    {"que_number": 78, "lv": 1, "kinds": "좌표평면"},
    {"que_number": 79, "lv": 2, "kinds": "좌표평면"},
    {"que_number": 80, "lv": 1, "kinds": "좌표평면"},
    {"que_number": 81, "lv": 0, "kinds": "자료 구조"},
    {"que_number": 82, "lv": 1, "kinds": "자료 구조"},
    {"que_number": 83, "lv": 1, "kinds": "자료 구조"},
    {"que_number": 84, "lv": 1, "kinds": "자료 구조"},
    {"que_number": 85, "lv": 1, "kinds": "자료 구조"},
    {"que_number": 86, "lv": 0, "kinds": "자료 구조"},
    {"que_number": 87, "lv": 0, "kinds": "숫자 교환"},
    {"que_number": 88, "lv": 0, "kinds": "숫자 변환"},
    {"que_number": 89, "lv": 2, "kinds": "선형대수"},
    {"que_number": 90, "lv": 0, "kinds": "기하학"},
    {"que_number": 91, "lv": 0, "kinds": "재귀"},
    {"que_number": 92, "lv": 0, "kinds": "재귀"},
    {"que_number": 93, "lv": 0, "kinds": "재귀"},
    {"que_number": 94, "lv": 0, "kinds": "재귀"},
    {"que_number": 95, "lv": 0, "kinds": "재귀"},
    {"que_number": 96, "lv": 0, "kinds": "재귀"},
    {"que_number": 97, "lv": 0, "kinds": "재귀"},
    {"que_number": 98, "lv": 2, "kinds": "백트래킹"},
    {"que_number": 99, "lv": 1, "kinds": "백트래킹"},
    {"que_number": 100, "lv": 1, "kinds": "문자열"}
]
